import type { Metadata } from 'next';
import '../globals.css';
import { NavBar } from '@/components/NavBar';
import { Footer } from '@/components/Footer';
import { LoadingLayout } from '@/components/Loading/LoadingLayout';


export const metadata: Metadata = {
  title: 'MovieFlix',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <LoadingLayout>
        <NavBar />
        {children}
        <Footer />
      </LoadingLayout>
    </>
  );
}
