import type { Metadata } from "next";
import "../../globals.css";
import { AOSInit } from "@/components/AOSInit";
import { Breadcrumb } from "@/components/Breadcrumb";
import { Sidebar } from "@/components/Sidebar";

export const metadata: Metadata = {
    title: "MovieFlix",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const breadcrumbItems = [
        { label: "Home", href: "/" },
        { label: "Oneshot", href: "/oneshot" },
        { label: "Shounen", href: "/gerne/shounen" },
        { label: "Sci-Fi", href: "/gerne/sci-fi" },
        { label: "Comedy", href: "/gerne/comedy" },
        { label: "Adventure", href: "/gerne/adventure" },
        { label: "Kids", href: "/gerne/kids" },
        { label: "Doraemon: Nobita's New Dinosaur", href: "#" },
        { label: "Infomation", href: "" },
    ];

    return (
        <div className="min-h-screen">
            <AOSInit />
            <div className="container mx-auto">
                <Breadcrumb items={breadcrumbItems} />
            </div>

            <main className="flex-1 py-6">
                <div className="container mx-auto px-4">
                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                        <div className="lg:col-span-9">
                            {children}
                        </div>
                        <aside className="lg:col-span-3">
                            <Sidebar />
                        </aside>
                    </div>
                </div>
            </main>
        </div>
    );
}