version: '3.8'
services:
  apigateway:
    image: apigateway:latest
    build:
      context: ./ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - userservice
      - movieservice
      - playbackservice
      - recommendationservice
      - elasticsearch

  userservice:
    image: userservice:latest
    build:
      context: ./UserService
    ports:
      - "7228:80"
    networks:
      - my_network

  movieservice:
    image: movieservice:latest
    build:
      context: ./MovieService
    ports:
      - "7225:80"
    networks:
      - my_network

  recommendationservice:
    image: recommendationservice:latest
    build:
      context: ./RecommendationService
    ports:
      - "7234:80"
    networks:
      - my_network

  searchservice:
    image: searchservice:latest
    build:
      context: ./SearchService
    ports:
      - "7227:80"
    networks:
      - my_network
      - es-net
    
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"   # Management UI
      - "15672:15672"   # Message Broker
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
  es-net:
    driver: bridge