version: '3.8'
services:
  apigateway:
    image: apigateway:latest
    build:
      context: ./ApiGateway
    ports:
      - "8000:80"
    depends_on:
      - userservice
      - movieservice
      - playbackservice
      - recommendationservice
      - searchservice
      - elasticsearch

  userservice:
    image: userservice:latest
    build:
      context: ./UserService
    ports:
      - "8001:80"
    networks:
      - my_network

  movieservice:
    image: movieservice:latest
    build:
      context: ./MovieService
    ports:
      - "8002:80"
    networks:
      - my_network

  playbackservice:
    image: playbackservice:latest
    build:
      context: ./PlaybackService
    ports:
      - "8003:80"
    networks:
      - my_network

  recommendationservice:
    image: recommendationservice:latest
    build:
      context: ./RecommendationService
    ports:
      - "8004:80"
    networks:
      - my_network

  searchservice:
    image: searchservice:latest
    build:
      context: ./SearchService
    ports:
      - "8005:80"
    networks:
      - my_network
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"   # Management UI
      - "15672:15672"   # Message Broker
    networks:
      - my_network
